# Generated by Django 4.0.5 on 2022-07-14 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_table',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_balance', models.BigIntegerField(null=True)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Fixed Deposit', 'Fixed Deposit')], max_length=20, null=True)),
                ('account_number', models.CharField(default=10101010, max_length=10, unique=True)),
                ('future_transaction', models.DateTimeField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_table',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_number', models.CharField(max_length=10, null=True)),
                ('recipient_number', models.CharField(max_length=10, null=True)),
                ('recipient_bank', models.CharField(max_length=20, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactionapp.account_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
