# Generated by Django 4.0.5 on 2022-07-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_table',
            name='account_pin',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
