# Generated by Django 4.0.5 on 2022-07-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0002_account_table_account_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_table',
            name='transaction_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
