# Generated by Django 4.0.5 on 2022-07-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0003_transaction_table_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_table',
            name='sender_account',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account_table',
            name='account_pin',
            field=models.IntegerField(default=0),
        ),
    ]
